
desc "Build data for tests"
lane :build_data_for_tests do |options|
  scan(
    scheme: "MyChat",
    clean: true,
    build_for_testing: true
  )
end

desc "Start tests"
lane :start_tests do |options|
  scan(
    scheme: "MyChat",
    test_without_building: true
  )
end

desc "Build and Run tests"
lane :build_and_run_tests do |options|
  build_data_for_tests
  start_tests
end