//
//  ConversationListViewController + Extension.swift
//  MyChat
//
//  Created by Konstantin Porokhov on 03.03.2021.
//

import Foundation

extension ConversationListViewController {
    var chats2: [MyChat]? {
        let chats: [MyChat] = [MyChat(name: "Peter Brown",
                               message: "Are you going to ride a bike today?",
                               date: Date(),
                               online: true, hasUnreadMessages: false),
                          MyChat(name: "Sarah White",
                               message: "Wow!",
                               date: Date(),
                               online: true, hasUnreadMessages: true),
                          MyChat(name: "Melven Sandro",
                               message: "Hello!",
                               date: Date().enterDate(hour: 16, minute: 20, day: 10),
                               online: true, hasUnreadMessages: false),
                          MyChat(name: "Michail Jordan",
                               message: "Hi man!",
                               date: Date(),
                               online: true, hasUnreadMessages: false),
                          MyChat(name: "Nike Rose",
                               message: "Nice to meet you",
                               date: Date(),
                               online: true, hasUnreadMessages: true),
                          MyChat(name: "Peter Croun",
                               message: "See you!",
                               date: Date(),
                               online: true, hasUnreadMessages: false),
                          MyChat(name: "Andrey Velvet",
                               message: "How much?",
                               date: Date().enterDate(hour: 14, minute: 5, day: 15),
                               online: true, hasUnreadMessages: false),
                          MyChat(name: "Ivan Korobov",
                               message: "Where are you?",
                               date: Date(),
                               online: true, hasUnreadMessages: false),
                          MyChat(name: "Sandra Key",
                               message: "What did you say?",
                               date: Date(),
                               online: true, hasUnreadMessages: false),
                          MyChat(name: "Olog Genegber",
                               message: "Hi, I'm Olog!",
                               date: Date(),
                               online: true, hasUnreadMessages: false),
                          MyChat(name: "Kasimus Aziris",
                                message: "mmm...",
                                date: Date().enterDate(hour: 10, minute: 45, day: 23),
                                online: false, hasUnreadMessages: false),
                           MyChat(name: "John Smith",
                                message: "I'm going to ride a bike today, and you?",
                                date: Date(),
                                online: false, hasUnreadMessages: false),
                           MyChat(name: "Michael Jackson",
                                message: nil,
                                date: Date(),
                                online: false, hasUnreadMessages: false),
                           MyChat(name: "Bender",
                                message: "Bite my shiny metal ass",
                                date: Date(),
                                online: false, hasUnreadMessages: false),
                           MyChat(name: "Philip Fry",
                                message: "Shit, that was the last beer. I'll kill you!",
                                date: Date(),
                                online: false, hasUnreadMessages: false),
                           MyChat(name: "Mozes Matues",
                                message: nil,
                                date: Date(),
                                online: false, hasUnreadMessages: false),
                           MyChat(name: "Nikol Kidman",
                                message: "Hi, I'm Niki!",
                                date: Date(),
                                online: false, hasUnreadMessages: true),
                           MyChat(name: "Arnold Schwarzenegger",
                                message: "I'll be back",
                                date: Date(),
                                online: false, hasUnreadMessages: false),
                           MyChat(name: "Peter Gray",
                                message: "Are you going to ride a bike today?",
                                date: Date(),
                                online: false, hasUnreadMessages: false),
                           MyChat(name: "John Brown",
                                message: "Are you going to ride a bike today?",
                                date: Date(),
                                online: false, hasUnreadMessages: false)
                        ]
    
        return chats
    }
}
