
name: CI
on: [push]
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        ruby-version: 2.6
        bundler-cache: true
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Test project"
        description: ${{ job.status }}
        username: Konstantin Porokhov

    - name: Build and run tests
      run: bundle exec fastlane build_and_run_tests
      
