
name: CI
on: [push]
jobs:
  build:
    runs-on: macOS-latest

    steps:
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    
    - name: Install bundler
      uses: actions/checkout@v2
        with:
          bundler-cache: true
    
    - name: Build and run tests
      run: bundle exec fastlane build_and_run_tests
      
    # - name: Send notification
    #   uses: sarisia/actions-status-discord@v1
    #   if: always()
    #   with:
    #     webhook: ${{ secrets.DISCORD_WEBHOOK }}
    #     title: "Test project"
    #     sername: Konstantin Porokhov